apiVersion: v1
kind: Pod
metadata:
  name: inference-liveness-readiness
spec:
  containers:
    - name: inference-liveness-readiness
      image: sanyacenter/ml_prod_server
      ports:
        - containerPort: 8000
      args:
        - /bin/bash
        - -c
        - "sleep 30; uvicorn app:app --host 0.0.0.0 --port 8000"
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10