apiVersion: v1
kind: Pod
metadata:
  name: inference-requests-limits
spec:
  containers:
    - name: inference-requests-limits
      image: sanyacenter/ml_prod_server
      resources:
        requests:
          memory: "100Mi"
          cpu: "200m"
        limits:
          memory: "200Mi"
          cpu: "400m"
      ports:
        - containerPort: 8000